tasks:
  - name: compile
    commands:
      - command: git.get_project
        params:
          directory: src
      - command: shell.exec
        params:
          working_dir: src
          script: |
            phpize

buildvariants:
- name: linux-64
  display_name: "Linux 64"
  run_on:
  - ubuntu1604-test
  tasks:
  - name: compile
 
