language: php

addons:
  apt:
    packages:
      - gdb
      - lcov

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      php: 5.5
    - os: linux
      dist: trusty
      sudo: required
      php: 5.6
    - os: linux
      dist: trusty
      sudo: required
      php: 7.0
    - os: linux
      dist: trusty
      sudo: required
      php: 7.1
    - os: linux
      dist: trusty
      sudo: required
      php: 7.2
    - os: osx
      osx_image: xcode8.3
      language: generic
      env:
        - PHP_VERSION: php56
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - PHP_VERSION: php72
    - os: osx
      osx_image: xcode9.2
      language: generic
      env:
        - PHP_VERSION: php72
        - SSL_VERSION: darwin

services:
  - mongodb

env:
  global:
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    - REPORT_EXIT_STATUS=1

before_install:
  - .travis.scripts/before_install.sh
  - php -r 'if ( ! ($f = php_ini_loaded_file())) { $f = PHP_CONFIG_FILE_PATH . "/php.ini"; } file_put_contents($f, "variables_order=EGPCS\n", FILE_APPEND); $a = file($f, FILE_IGNORE_NEW_LINES); var_dump($a[count($a)-1]);'

before_script:
  - ulimit -a
  - ulimit -c unlimited || true
  - .travis.scripts/before_script.sh

script:
  - make test

after_success:
  - make coveralls

after_failure:
  - find . -name 'core*' -exec .travis.scripts/debug-core.sh {} \;
  - find . -name '*.diff' -exec .travis.scripts/debug-diff.sh {} \;
