language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5

services:
  - mongodb

env:
  global:
    - TEST_PHP_ARGS="-q -s output.txt -g XFAIL,FAIL,BORK,WARN,LEAK,SKIP -x --show-diff"
    - REPORT_EXIT_STATUS=1

before_install:
  - sudo pip install --upgrade cpp-coveralls
  - sudo apt-get update
  - sudo apt-get install gdb valgrind
  - sudo apt-get install cdbs debhelper build-essential python-lxml
  - php -r 'if ( ! ($f = php_ini_loaded_file())) { $f = PHP_CONFIG_FILE_PATH . "/php.ini"; } file_put_contents($f, "variables_order=EGPCS\n", FILE_APPEND); $a = file($f, FILE_IGNORE_NEW_LINES); var_dump($a[count($a)-1]);'

before_script:
  - ulimit -a
  - ulimit -c unlimited || true
  - "./.travis.scripts/compile.sh"

script:
  - make test

after_success:
  - make coveralls

after_failure:
  - find . -name \*core\* -exec ./.travis.scripts/debug-core.sh {} \;
  - find . -name \*diff -exec ./.travis.scripts/debug-script.sh {} \;
